/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
export function Model(props) {
  const { nodes, materials } = useGLTF("/test.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_shiwai_chedaoxian.geometry}
        material={materials.dhsthjydtyj}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_shiwai_tingchechang.geometry}
        material={materials.sgag}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_waijin_biankuang.geometry}
        material={materials["23 - Default"]}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_waijin_renxingdao.geometry}
        material={materials.DMB}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object017.geometry}
        material={materials.rrgargqaerg}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object018.geometry}
        material={materials.awrfarg}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object020.geometry}
        material={materials.awrfarg}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object021.geometry}
        material={materials.rrgargqaerg}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object016.geometry}
        material={materials.GXGY_shiwai_hongqi}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_waijin_dimian.geometry}
        material={materials.GXGY_waijin_dimian}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_waijin_malu.geometry}
        material={materials.GXGY_shiwai_malu}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_shiwai_renxingdao.geometry}
        material={materials.GXGY_shiwai_renxingdao}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_shiwai_caodi.geometry}
        material={materials.GXGY_shiwai_caodi}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_jianzhu_biankuang.geometry}
        material={materials.GXGY_jianzhu_biankuang}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_shiwai_dimian.geometry}
        material={materials["GXGY_waijin_dimian.001"]}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_jianzhu_louding.geometry}
        material={materials.GXGY_jianzhu_louding}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_jianzhu_tiaowen.geometry}
        material={materials.GXGY_jianzhu_tiaowen}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_waijin_jianzhu.geometry}
        material={materials["Material #797"]}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_jianzhu_chuangkuang.geometry}
        material={materials.GXGY_jianzhu_chuangkuang}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_jianzhu_boli001.geometry}
        material={materials.GXGY_jianzhu_boli}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_jianzhu_loudingbiankuang.geometry}
        material={materials["Material #762"]}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_sjiwai_shu.geometry}
        material={materials["Material #761"]}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_shiwai_qiche.geometry}
        material={materials["Material #760"]}
        position={[-4.23, 0, 0.61]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GXGY_jianzhu_louti.geometry}
        material={materials.GXGY_jianzhu_louti}
        position={[-4.23, 0, 0.61]}
      />
    </group>
  );
}

useGLTF.preload("/test.glb");
